steps:
  - id: Echo Substitutions (variables)
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash' 
    args:
      - '-c'
      - |       
        echo "AR_HOSTNAME:$_AR_HOSTNAME"
        echo "PROJECT_ID:$PROJECT_ID"
        echo "REPO_NAME:$REPO_NAME"
        echo "SERVICE_NAME:$_SERVICE_NAME"
        echo "SHORT_SHA:$SHORT_SHA"
        echo "PORT:$_PORT"
        echo "ENV:$_ENV"
        echo "SITE:$_SITE"
        echo "COUNTRY:$_COUNTRY"
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - SITE=${_SITE}
      - '--build-arg'
      - COUNTRY=${_COUNTRY}
      - '--build-arg'
      - STAGE=${_ENV}
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TRIGGER_ID: 15666bd3-3ac7-4ee3-ad89-72cc579d5d65
  _DEPLOY_REGION: asia-east1
  _AR_HOSTNAME: asia-east1-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: playbuz-front
  _ENV: qa
  _SITE: playbuz
  _COUNTRY: tw
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - playbuz-front
