// 使否啟用靜態遊戲資訊
const isUseStaticList = true

// 靜態遊戲
export const GAME_STATIC_LIST = [
  // {
  //   GameID: 99998,
  //   GameName: 'inPoker_正體中文版',
  //   SubTitle: 'inPoker出app啦！前往app store馬上下載',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'eden_102',
  //     GameUrl: '',
  //     IOSUrl: 'https://apps.apple.com/tw/app/inpoker-%E6%AD%A3%E9%AB%94%E4%B8%AD%E6%96%87%E7%89%88/id1591578712',
  //     AndroidUrl: '',
  //   },
  // },
  // {
  //   GameID: 99997,
  //   GameName: '烈焰戰紀',
  //   SubTitle: '不管哪個世代都能體驗MMO RPG的快感',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 're_01',
  //     GameUrl: '',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99996,
  //   GameName: '娜娜的奇幻冒險 RE',
  //   SubTitle: '你將扮演戰鬥節奏指揮官和娜娜一起冒險',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 're_02',
  //     GameUrl: '',
  //     IOSUrl: 'https://apps.apple.com/tw/app/id1551925298',
  //     AndroidUrl: 'https://play.google.com/store/apps/details?id=com.runewaker.lunaex&hl=zh-tw',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99995,
  //   GameName: '輻射塔防',
  //   SubTitle: '小編精選：App Store上的爆款',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_05',
  //     GameUrl: '',
  //     IOSUrl: 'https://apps.apple.com/tw/app/%E8%BC%BB%E5%B0%84%E5%A1%94%E9%98%B2/id512203663',
  //     AndroidUrl: 'https://play.google.com/store/apps/details?id=net.hexage.defense&hl=zh_TW&gl=US',
  //   },
  //   mediaUrl: [
  //     {
  //       type: 'image',
  //       src: process.env.VUE_APP_IMG_URL + '/img/game/static/mobile/type_short/other_05.jpg',
  //     },
  //     {
  //       id: 'GBfQhcRBoB4',
  //       type: 'youtube',
  //       src: 'https://www.youtube.com/watch?v=GBfQhcRBoB4',
  //     }],
  //   isRecommend: true,
  // },
  // {
  //   GameID: 99994,
  //   GameName: '喋血復仇',
  //   SubTitle: '小編推薦：懷念惡靈勢力嗎？',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_06',
  //     GameUrl: 'https://back4blood.com/zh-tw',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99993,
  //   GameName: '因狄斯的謊言',
  //   SubTitle: '小編精選：喜歡地下城卡牌遊戲不可錯過',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_09',
  //     GameUrl: '',
  //     IOSUrl: 'https://apps.apple.com/tw/app/%E5%9B%A0%E7%8B%84%E6%96%AF%E7%9A%84%E8%AC%8A%E8%A8%80/id1573371456',
  //     AndroidUrl: 'https://play.google.com/store/apps/details?id=com.yokagame.ProjectS&hl=zh_TW&gl=US',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99992,
  //   GameName: '貓咪大戰爭',
  //   SubTitle: '小編精選：2022也要繼續擼貓',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_07',
  //     GameUrl: '',
  //     IOSUrl: 'https://apps.apple.com/tw/app/%E8%B2%93%E5%92%AA%E5%A4%A7%E6%88%B0%E7%88%AD/id971601423',
  //     AndroidUrl: 'https://play.google.com/store/apps/details?id=jp.co.ponos.battlecatstw&referrer=utm_source%3Dgamer.com.tw%26utm_campaign%3Dacgdb',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99991,
  //   GameName: '鬼線：東京',
  //   SubTitle: '小編精選：三上真司全新力作',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_08',
  //     GameUrl: 'https://bethesda.net/zh-TW/game/ghostwire-tokyo',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   mediaUrl: [
  //     {
  //       type: 'image',
  //       src: process.env.VUE_APP_IMG_URL + '/img/game/static/mobile/type_short/other_08.jpg',
  //     },
  //     {
  //       id: '9X05r9TiGXc',
  //       type: 'youtube',
  //       src: 'https://www.youtube.com/watch?v=9X05r9TiGXc',
  //     }],
  //   isRecommend: true,
  // },
  // {
  //   GameID: 99990,
  //   GameName: '五龍爭霸',
  //   SubTitle: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_10',
  //     GameUrl: '',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  // },
  // {
  //   GameID: 99989,
  //   GameName: 'Apex 英雄',
  //   SubTitle: '小編精選：成為英雄主宰競技場',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_10',
  //     GameUrl: 'https://www.ea.com/zh-tw/games/apex-legends',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99988,
  //   GameName: '魔物獵人 崛起：破曉',
  //   SubTitle: '小編擼貓：修女貓貓絕對是最香的選擇！',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_11',
  //     GameUrl: 'https://www.monsterhunter.com/rise-sunbreak/zh-hk/action/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99987,
  //   GameName: '跑車浪漫旅 7',
  //   SubTitle: '小編精選：握好你的方向盤',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_12',
  //     GameUrl: 'https://www.playstation.com/zh-hant-tw/games/gran-turismo-7/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99986,
  //   GameName: '第七史詩',
  //   SubTitle: '小編精選：成為繼承者大人吧',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_13',
  //     GameUrl: 'https://epic7.smilegatemegaport.com/brand/tw',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99985,
  //   GameName: '昆特牌：異始法師',
  //   SubTitle: '遊戲新報：【巫師3】本體的新作',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_14',
  //     GameUrl: 'https://store.steampowered.com/app/1711950/_/?l=tchinese',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99984,
  //   GameName: '賽馬娘',
  //   SubTitle: '小編精選：盡情享受競技育成樂趣吧',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_15',
  //     GameUrl: 'https://uma.komoejoy.com/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99983,
  //   GameName: '暗黑破壞神永生不朽',
  //   SubTitle: '遊戲新報：你們沒有手機嗎？',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_16',
  //     GameUrl: 'https://diabloimmortal.blizzard.com/zh-tw/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99982,
  //   GameName: '決勝時刻®：現代戰爭® II 2022',
  //   SubTitle: '經典槍戰，即刻呈現沉浸式多人遊戲戰鬥！',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_20',
  //     GameUrl: 'https://store.steampowered.com/app/1938090/_II_2022/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99981,
  //   GameName: '斯普拉遁 3',
  //   SubTitle: '超魷型玩家！你是塗鴉派還是射擊派？',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_21',
  //     GameUrl: 'https://www.nintendo.com.hk/switch/av5ja/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99980,
  //   GameName: '勇者鬥惡龍',
  //   SubTitle: '尋寶探險團：藍色眼眸與天空羅盤',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_22',
  //     GameUrl: 'https://store.nintendo.com.hk/70010000038932',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99979,
  //   GameName: '寶可夢 朱紫',
  //   SubTitle: '探索帕底亞地區，感受第九世代的全新冒險',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_23',
  //     GameUrl: 'https://www.pokemon.co.jp/ex/sv/tc/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99978,
  //   GameName: '戰神 諸神黃昏',
  //   SubTitle: '在這場神話之旅中大戰四方吧！',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_24',
  //     GameUrl: 'https://www.playstation.com/zh-hant-tw/god-of-war/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99977,
  //   GameName: '洶湧海豚',
  //   SubTitle: '洶湧海豚，胸勇無比！與勁敵之間的熱血戰鬥！',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_25',
  //     GameUrl: 'https://www.hpgames.jp/dolphin-wave/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99976,
  //   GameName: '浩劫前夕',
  //   SubTitle: '你面對的不僅是那些感染者⋯。',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_26',
  //     GameUrl: 'https://www.daybeforegame.com/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99975,
  //   GameName: '阿凡達：潘多拉邊境',
  //   SubTitle: '育碧、光影風暴娛樂以及迪士尼合作開發大作！',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_27',
  //     GameUrl: 'https://www.ubisoft.com/zh-tw/game/avatar-frontiers-of-pandora',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99974,
  //   GameName: '動物朋友：王國',
  //   SubTitle: '活潑的獸娘們讓您感受到陽光的正面能量。',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_28',
  //     GameUrl: 'https://kfk.game-beans.com/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99973,
  //   GameName: 'Among Us VR',
  //   SubTitle: '享受VR 版獨有的太空狼人殺樂趣吧！',
  //   Detailed: '',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_29',
  //     GameUrl: 'https://www.oculus.com/experiences/quest/4948428055244413/?locale=zh_TW',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  //   isRecommend: false,
  // },
  // {
  //   GameID: 99972,
  //   GameName: '老虎娛樂城',
  //   SubTitle: '老虎機、捕魚機、美好體驗經典重現！',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_30',
  //     GameUrl: 'https://www.playloong.com/tiger/',
  //     IOSUrl: '',
  //     AndroidUrl: '',
  //   },
  // },
  // {
  //   GameID: 99971,
  //   GameName: '星雲歡樂城',
  //   SubTitle: '不用再等良辰吉時,馬上享受幸運嗨到頂 !',
  //   GameType: '',
  //   Vendor: {
  //     ID: 'other_99971',
  //     GameUrl: '',
  //     IOSUrl: 'https://apps.apple.com/tw/app/%E6%98%9F%E9%9B%B2%E6%AD%A1%E6%A8%82%E5%9F%8E-%E9%BA%BB%E5%B0%87%E6%92%B2%E5%85%8B%E8%80%81%E8%99%8E%E6%A9%9F-%E6%B2%88%E7%8E%89%E7%90%B3-%E6%9E%97%E8%A5%84%E4%B8%80%E8%B5%B7%E6%8E%A8%E8%96%A6/id1507308071',
  //     AndroidUrl: 'https://play.google.com/store/apps/details?id=com.deepspace.qiqilaiyifan&hl=zh_TW&gl=US',
  //   },
  // },
]

const gameStaticList = !isUseStaticList
  ? []
  : GAME_STATIC_LIST.map(item => {
      return { ...item, IsStatic: true }
    })

export const STATIC_GAME_LIST = gameStaticList
